/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as AiStyleTransferRouteImport } from './routes/ai.style-transfer'
import { Route as AiSettingsRouteImport } from './routes/ai.settings'
import { Route as AiSceneRouteImport } from './routes/ai.scene'
import { Route as AiPromptsRouteImport } from './routes/ai.prompts'
import { Route as AiPlanRouteImport } from './routes/ai.plan'
import { Route as AiMangaPageRouteImport } from './routes/ai.manga-page'
import { Route as AiHistoryRouteImport } from './routes/ai.history'
import { Route as AiCharactersRouteImport } from './routes/ai.characters'
import { Route as AiChapterRouteImport } from './routes/ai.chapter'
import { Route as AiAssetsRouteImport } from './routes/ai.assets'

const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiRoute,
} as any)
const AiStyleTransferRoute = AiStyleTransferRouteImport.update({
  id: '/style-transfer',
  path: '/style-transfer',
  getParentRoute: () => AiRoute,
} as any)
const AiSettingsRoute = AiSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AiRoute,
} as any)
const AiSceneRoute = AiSceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => AiRoute,
} as any)
const AiPromptsRoute = AiPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AiRoute,
} as any)
const AiPlanRoute = AiPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AiRoute,
} as any)
const AiMangaPageRoute = AiMangaPageRouteImport.update({
  id: '/manga-page',
  path: '/manga-page',
  getParentRoute: () => AiRoute,
} as any)
const AiHistoryRoute = AiHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AiRoute,
} as any)
const AiCharactersRoute = AiCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => AiRoute,
} as any)
const AiChapterRoute = AiChapterRouteImport.update({
  id: '/chapter',
  path: '/chapter',
  getParentRoute: () => AiRoute,
} as any)
const AiAssetsRoute = AiAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/ai/assets': typeof AiAssetsRoute
  '/ai/chapter': typeof AiChapterRoute
  '/ai/characters': typeof AiCharactersRoute
  '/ai/history': typeof AiHistoryRoute
  '/ai/manga-page': typeof AiMangaPageRoute
  '/ai/plan': typeof AiPlanRoute
  '/ai/prompts': typeof AiPromptsRoute
  '/ai/scene': typeof AiSceneRoute
  '/ai/settings': typeof AiSettingsRoute
  '/ai/style-transfer': typeof AiStyleTransferRoute
  '/ai/': typeof AiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai/assets': typeof AiAssetsRoute
  '/ai/chapter': typeof AiChapterRoute
  '/ai/characters': typeof AiCharactersRoute
  '/ai/history': typeof AiHistoryRoute
  '/ai/manga-page': typeof AiMangaPageRoute
  '/ai/plan': typeof AiPlanRoute
  '/ai/prompts': typeof AiPromptsRoute
  '/ai/scene': typeof AiSceneRoute
  '/ai/settings': typeof AiSettingsRoute
  '/ai/style-transfer': typeof AiStyleTransferRoute
  '/ai': typeof AiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/ai/assets': typeof AiAssetsRoute
  '/ai/chapter': typeof AiChapterRoute
  '/ai/characters': typeof AiCharactersRoute
  '/ai/history': typeof AiHistoryRoute
  '/ai/manga-page': typeof AiMangaPageRoute
  '/ai/plan': typeof AiPlanRoute
  '/ai/prompts': typeof AiPromptsRoute
  '/ai/scene': typeof AiSceneRoute
  '/ai/settings': typeof AiSettingsRoute
  '/ai/style-transfer': typeof AiStyleTransferRoute
  '/ai/': typeof AiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/ai/assets'
    | '/ai/chapter'
    | '/ai/characters'
    | '/ai/history'
    | '/ai/manga-page'
    | '/ai/plan'
    | '/ai/prompts'
    | '/ai/scene'
    | '/ai/settings'
    | '/ai/style-transfer'
    | '/ai/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai/assets'
    | '/ai/chapter'
    | '/ai/characters'
    | '/ai/history'
    | '/ai/manga-page'
    | '/ai/plan'
    | '/ai/prompts'
    | '/ai/scene'
    | '/ai/settings'
    | '/ai/style-transfer'
    | '/ai'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/ai/assets'
    | '/ai/chapter'
    | '/ai/characters'
    | '/ai/history'
    | '/ai/manga-page'
    | '/ai/plan'
    | '/ai/prompts'
    | '/ai/scene'
    | '/ai/settings'
    | '/ai/style-transfer'
    | '/ai/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/': {
      id: '/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/style-transfer': {
      id: '/ai/style-transfer'
      path: '/style-transfer'
      fullPath: '/ai/style-transfer'
      preLoaderRoute: typeof AiStyleTransferRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/settings': {
      id: '/ai/settings'
      path: '/settings'
      fullPath: '/ai/settings'
      preLoaderRoute: typeof AiSettingsRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/scene': {
      id: '/ai/scene'
      path: '/scene'
      fullPath: '/ai/scene'
      preLoaderRoute: typeof AiSceneRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/prompts': {
      id: '/ai/prompts'
      path: '/prompts'
      fullPath: '/ai/prompts'
      preLoaderRoute: typeof AiPromptsRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/plan': {
      id: '/ai/plan'
      path: '/plan'
      fullPath: '/ai/plan'
      preLoaderRoute: typeof AiPlanRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/manga-page': {
      id: '/ai/manga-page'
      path: '/manga-page'
      fullPath: '/ai/manga-page'
      preLoaderRoute: typeof AiMangaPageRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/history': {
      id: '/ai/history'
      path: '/history'
      fullPath: '/ai/history'
      preLoaderRoute: typeof AiHistoryRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/characters': {
      id: '/ai/characters'
      path: '/characters'
      fullPath: '/ai/characters'
      preLoaderRoute: typeof AiCharactersRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/chapter': {
      id: '/ai/chapter'
      path: '/chapter'
      fullPath: '/ai/chapter'
      preLoaderRoute: typeof AiChapterRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/assets': {
      id: '/ai/assets'
      path: '/assets'
      fullPath: '/ai/assets'
      preLoaderRoute: typeof AiAssetsRouteImport
      parentRoute: typeof AiRoute
    }
  }
}

interface AiRouteChildren {
  AiAssetsRoute: typeof AiAssetsRoute
  AiChapterRoute: typeof AiChapterRoute
  AiCharactersRoute: typeof AiCharactersRoute
  AiHistoryRoute: typeof AiHistoryRoute
  AiMangaPageRoute: typeof AiMangaPageRoute
  AiPlanRoute: typeof AiPlanRoute
  AiPromptsRoute: typeof AiPromptsRoute
  AiSceneRoute: typeof AiSceneRoute
  AiSettingsRoute: typeof AiSettingsRoute
  AiStyleTransferRoute: typeof AiStyleTransferRoute
  AiIndexRoute: typeof AiIndexRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiAssetsRoute: AiAssetsRoute,
  AiChapterRoute: AiChapterRoute,
  AiCharactersRoute: AiCharactersRoute,
  AiHistoryRoute: AiHistoryRoute,
  AiMangaPageRoute: AiMangaPageRoute,
  AiPlanRoute: AiPlanRoute,
  AiPromptsRoute: AiPromptsRoute,
  AiSceneRoute: AiSceneRoute,
  AiSettingsRoute: AiSettingsRoute,
  AiStyleTransferRoute: AiStyleTransferRoute,
  AiIndexRoute: AiIndexRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
